// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOdpEQFFdLfgRxEQRvyUQ7IHYzW72KAo',
    appId: '1:715064744367:web:f1f83f318c86adff25375a',
    messagingSenderId: '715064744367',
    projectId: 'adminpage-63417',
    authDomain: 'adminpage-63417.firebaseapp.com',
    storageBucket: 'adminpage-63417.firebasestorage.app',
    measurementId: 'G-FCME42VJ90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMHeDVwGXosILZmrffz6bHSTbqO_bBuA',
    appId: '1:982401879467:android:043f6e395435a5fcd056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOdpEQFFdLfgRxEQRvyUQ7IHYzW72KAo',
    appId: '1:715064744367:web:861e3a5a496f92fe25375a',
    messagingSenderId: '715064744367',
    projectId: 'adminpage-63417',
    authDomain: 'adminpage-63417.firebaseapp.com',
    storageBucket: 'adminpage-63417.firebasestorage.app',
    measurementId: 'G-S9TTDHRS9P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUVX8-cHINej4dgpRLeth0W33dqcCSZY',
    appId: '1:982401879467:ios:3879ea8ad5414da7d056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

}